// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk0dIf-jvYrq12tSTLxkPPx8hA94s2zwo',
    appId: '1:869875364400:web:b2816fc7b7e195022773f5',
    messagingSenderId: '869875364400',
    projectId: 'zoom-clone-f8e72',
    authDomain: 'zoom-clone-f8e72.firebaseapp.com',
    storageBucket: 'zoom-clone-f8e72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW7FPDQiYbUnb7d8BEhPx9OjanMA5jUkM',
    appId: '1:869875364400:android:73099a3aae1a22762773f5',
    messagingSenderId: '869875364400',
    projectId: 'zoom-clone-f8e72',
    storageBucket: 'zoom-clone-f8e72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2rJVKRpPFXXXxR-U8dyju6edLKnslo7o',
    appId: '1:869875364400:ios:6646ede6fc29b58b2773f5',
    messagingSenderId: '869875364400',
    projectId: 'zoom-clone-f8e72',
    storageBucket: 'zoom-clone-f8e72.appspot.com',
    iosClientId: '869875364400-kpf6tdtpt9tinmi5j4kb7eh2cusirla0.apps.googleusercontent.com',
    iosBundleId: 'com.rishi.zoomClone',
  );
}
